### ISSUE TITLE
Debian 11/Bullseye: No package matching 'python-apt' is available

### ISSUE THREAD

**Issue by christophkreutzer** [artis3n/ansible-role-tailscale#124]
Now that bullseye is no longer `testing`, the following condition fails: https://github.com/artis3n/ansible-role-tailscale/blob/20f936327f0df3955e050eb6e30127caf7eddef6/tasks/debian.yml#L17

```bes
TASK [artis3n.tailscale : Debian | Legacy Apt Dependencies] ********************************************************************************************************************
fatal: [xxx]: FAILED! => {"changed": false, "msg": "No package matching 'python-apt' is available"}
```

I'm not sure what the best solution would be to update that condition, as it should match all the distributions...

In my personal debian base role, I have the following shell task:
```
"apt update; RC=$?; [ \"$RC\" = \"100\" ] || [ \"$RC\" = \"0\" ] && apt install -y python{{ ansible_python['version']['major'] if ansible_python['version']['major'] > 2 }}-apt"
```
Thats definitely not the cleanest solution, however after a fresh installation of Proxmox VE the apt update fails (Enterprise repo without accompanying credentials configured), so the apt module can't handle it itself without failing.

**Comment by artis3n** [comment]
Hey, good catch. I'm going to set up https://github.com/artis3n/docker-debian11-ansible on a cron schedule to regularly take in upstream updates to catch issues like this in CI. May be a week or two before a fix is in, depending on my schedule.

**Comment by shepherdjerred** [comment]
I'm a bit confused on this condition:
```
  when: (ansible_distribution_major_version | int < 20) and ansible_distribution_major_version != "testing"
```

It seems that the [latest version of Debian is 13 (Trixie)](https://wiki.debian.org/DebianReleases). Does that means that all versions of Debian are considered legacy? If so, then what's the point in differentiating between legacy and non-legacy if the same action is always taken?

**Comment by artis3n** [comment]
Ubuntu falls within the `debian.yml` family of distros. Ubuntu 20.04 is `ansible_distribution_major_version` = 20. So this is applying the check for all Debian distros minus Ubuntu distros. legacy was more of my cheeky mindset with debian distros having an old reliance on python2

**Comment by shepherdjerred** [comment]
Ah, makes sense.

I used this role on a fresh install of Debian 11 (Bullseye). I overrode `legacy_apt_dependencies` to install `python3-apt` instead of `python-apt` (which is redundant since `apt_dependencies` already installs this package -- my goal was simply to not install `python-apt`). The result was a working installation of Tailscale.

See: https://github.com/shepherdjerred/ansible-playbook/blob/master/main.yml#L16

**Comment by artis3n** [comment]
Luckily the error means that bullseye dropped python 2 requirements during its testing period, so it can join all modern distros with a tweak to that conditional.

**Comment by artis3n** [comment]
Ok `v1.13.1` is released to Ansible Galaxy with a fix for this. Thanks for both of your assistance!
