### ISSUE TITLE
Support Rocky Linux

### ISSUE THREAD

**Issue by artis3n** [artis3n/ansible-role-tailscale#172]
https://hub.docker.com/_/rockylinux

Centos 8 has reached EOL. Make sure OS resolution tasks support Rocky Linux in the CentOS family of distros instead.

**Comment by jaboutboul** [comment]
And AlmaLinux?

**Comment by artis3n** [comment]
Want to be mindful because neither of these are listed in Tailscale's supported distros but should be low effort to include. Sure, can you file a separate ticket for that distro?

https://tailscale.com/kb/1031/install-linux/
