### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by artis3n** [artis3n/ansible-role-tailscale#22]
Ansible 2.9 - <https://docs.ansible.com/ansible/2.9/modules/win_package_module.html>
Ansible 2.10 - <https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_package_module.html>

<https://tailscale.com/kb/1022/install-windows>

**Comment by artis3n** [comment]
This action only support Linux-based distros. Windows and OSX users should use the GUI installations or find another role.

**Comment by loprima-l** [comment]
Would you be intrested in a port of your playbook on widows ? I plan doing it at some point

**Comment by artis3n** [comment]
I would be - if it makes sense, it could be integrated into this role as a contribution, but you could make an adaptation as well. The repo is MIT licensed :)
