### ISSUE TITLE
[FEAT] Optionally, don't always upgrade tailscale to the latest version

### ISSUE THREAD

**Issue by relrod** [artis3n/ansible-role-tailscale#239]
**Is your feature request related to a problem? Please describe.**

I would like to be able to run this role and ensure all the configuration is in place and so on, but not necessarily have the package upgraded to the latest version unexpectedly.

Basically I would like the change in #116 to be optional, controlled by a variable.

**Describe the solution you'd like**
I'd like to be able to control if tailscale gets installed with `state: latest` or `state: present`, by setting a variable.

**Describe alternatives you've considered**
N/A

**Additional context**
My current usecase is that I run a playbook in check mode (automated) to check for configuration drift. I would like that playbook to not complain about a change just because there is a new release (which would get installed, and is currently legitimate configuration drift).

In some places it is fine, but on production systems, I like to sometimes do updates in batches and have control over them myself.

Thanks for the awesome work maintaining this, by the way. This is such a useful role.

**Comment by artis3n** [comment]
I am going to leave `state: latest` as the default behavior, but I agree! This should be configurable.

**Comment by relrod** [comment]
@artis3n thank you for this, you're awesome!
