### ISSUE TITLE
[BUG] No checking if system supports TUN adapters 

### ISSUE THREAD

**Issue by Jamdoog** [artis3n/ansible-role-tailscale#263]
**Describe the bug**
Lack of checking if TUN kernel module is available

**To Reproduce**
1. Deploy container-based server (ex. OVZ)
2. Run the role

**Expected behavior**
I expect the role to error early on with a message saying TUN kernel module is required

**Screenshots**
root@cdg:~# journalctl -xe
Dec 04 11:42:59 cdg tailscaled[8439]: logger closing down
Dec 04 11:43:00 cdg tailscaled[8449]: logtail started
Dec 04 11:43:00 cdg tailscaled[8449]: Program starting: v1.32.3-ta07555f43-g093d1e978, Go 1.19.2-ts3fd24dee31: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailsc
Dec 04 11:43:00 cdg tailscaled[8449]: LogID: e92f5b48cb44249d26fed8efe5fab1af987f268626f6e6f4ca134a159e3856d5
Dec 04 11:43:00 cdg tailscaled[8449]: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
Dec 04 11:43:00 cdg tailscaled[8449]: wgengine.NewUserspaceEngine(tun "tailscale0") ...
Dec 04 11:43:00 cdg tailscaled[8449]: Linux kernel version: 3.10.0-1160.53.1.vz7.185.3
Dec 04 11:43:00 cdg tailscaled[8449]: is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.
Dec 04 11:43:00 cdg tailscaled[8449]: modprobe: FATAL: Module tun not found in directory /lib/modules/3.10.0-1160.53.1.vz7.185.3
Dec 04 11:43:00 cdg tailscaled[8449]: tun module not loaded nor found on disk
Dec 04 11:43:00 cdg tailscaled[8449]: wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): operation not permitted
Dec 04 11:43:00 cdg tailscaled[8449]: flushing log.
Dec 04 11:43:00 cdg tailscaled[8449]: logger closing down
Dec 04 11:43:00 cdg tailscaled[8449]: createEngine: tstun.New("tailscale0"): operation not permitted

root@cdg:~# modprobe tun
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.10.0-1160.53.1.vz7.185.3/modules.builtin.bin'
modprobe: FATAL: Module tun not found in directory /lib/modules/3.10.0-1160.53.1.vz7.185.3

**Target (please complete the following information):**
 - OS: n/a
 - Ansible version: n/a
 - `artis3n.tailscale` version: Latest
 - Tailscale version (set `verbose` to true): n/a

**Additional context**
Just wanted to document this error here.

I will create a PR with a check soon.

**Comment by Jamdoog** [comment]
Fix: https://github.com/artis3n/ansible-role-tailscale/pull/264

**Comment by artis3n** [comment]
Left a comment on the PR - https://github.com/artis3n/ansible-role-tailscale/pull/264#issuecomment-1336432850

I don't believe the TUN module is required - https://tailscale.com/kb/1177/kernel-vs-userspace-routers/ and https://tailscale.com/kb/1112/userspace-networking/ . My preference would be to leave the determination of whether kernel or usermode operation is desired to the end user.

Going to close the issue, but it will be unlocked for further discussion if I'm wrong about this.
