### ISSUE TITLE
[BUG] Fedora: ansible role fails when systemd is degraded

### ISSUE THREAD

**Issue by zoenglinghou** [artis3n/ansible-role-tailscale#275]
**Describe the bug**
If my systemd status is degraded, i.e. `systemctl is-system-running` returns degraded and non-zero return code, task `Fedora | Wait for systemd to complete initialization.` fails.

**To Reproduce**
1. Have a `systemd` service failure
2. Run the role
3. See error:
```
TASK [ansible-tailscale : Fedora | Wait for systemd to complete initialization.] **********************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  attempts: 1
  cmd:
  - systemctl
  - is-system-running
  delta: '0:00:00.006059'
  end: '2022-12-10 11:24:32.714114'
  msg: non-zero return code
  rc: 1
  start: '2022-12-10 11:24:32.708055'
  stderr: ''
  stderr_lines: <omitted>
  stdout: degraded
  stdout_lines: <omitted>
```

**Expected behavior**
Role continues running even if sytemd service is degraded

**Screenshots**

**Target (please complete the following information):**
 - OS: Fedora
 - Ansible version: core 2.14.0
 - `artis3n.tailscale` version: 3.4.0
 - Tailscale version (set `verbose` to true):
 ```
1.34.0
  tailscale commit: bb6e746f335b45c0b103345c88a8ba9e0fba0e1a
  other commit: 8d1edab6f4eb0c28a9e64f7919b7e19a24beaa57
  go version: go1.19.2-ts3fd24dee31
```

Output of `tailscale status` during role execution (set `verbose` to true):
tailscale was already running.

**Additional context**

**Comment by artis3n** [comment]
Can you elaborate more on your use case? If systems is degraded, `tailscaled` will not be able to start and tailscale will be unable to run.

**Comment by zoenglinghou** [comment]
I was running the playbook on my laptop, and my `nvidia-powerd` service failed. `systemd` was therefore degraded with an rc of 1, but `tailscaled` should and will run.

**Comment by zoenglinghou** [comment]
The task is here: https://github.com/artis3n/ansible-role-tailscale/blob/a60ff5d3bba8b57b56b3a9404d62bf2d265df7d0/tasks/fedora/install.yml#L3-L12

I think `degraded` is an acceptable state for the installation to proceed, but because the `rc` is 1, the command would fail instead.

**Comment by artis3n** [comment]
Ah, I didn't look at my task before responding to you :) 

This makes sense, I'll explore a conditional failed_when.

**Comment by JonathanPorta** [comment]
I disabled and stopped the `nvidia-powered` service and then ran `systemctl reset-failed` to clear the degraded status.

**Comment by artis3n** [comment]
Intermittent reproduction in tests: https://github.com/artis3n/ansible-role-tailscale/actions/runs/4931556721/jobs/8813704921?pr=328#step:7:253

**Comment by artis3n** [comment]
This should be fixed when I next release this role
