### ISSUE TITLE
[FEAT] Create state directory in XDG_STATE_HOME

### ISSUE THREAD

**Issue by artis3n** [artis3n/ansible-role-tailscale#276]
This role currently creates a state folder in the user's home directory. Instead, we should follow <https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html> and create it in `$XDG_STATE_HOME`. If not defined, the default should be `$HOME/.local/state`.

Can write this into the role in a backwards-compatible manner but it will be simpler to make it a "breaking" change and release a major version. Since I am lazy, I will likely do that :) The backwards-compatible manner involves checking both locations for the statefile and applying a `state: absent` once the state is located and migrated to the new location. The "breaking" change would cause this role to report as `changed` incorrectly once as the statefile is moved to the new location. So not really breaking anything but I believe a strict adherence to semver still necessitates a major version bump.

**Comment by SebDanielsson** [comment]
Hi! Very welcome change. One question? Will I need to set the state to absent and then re-run with present to move the file to the new location? Just ran my playbook with the new version and the state file is still in the home dir😊

**Comment by artis3n** [comment]
Huh, it should have removed the old directory - https://github.com/artis3n/ansible-role-tailscale/blob/main/tasks/install.yml

**Comment by SebDanielsson** [comment]
Mistake on my part. Updated my requirements.yaml but never ran the upgrade. Started playing with Ansible a couple of weeks ago so I'm still kind of a noob😉 Everything is working as expected!
