### ISSUE TITLE
Allow for selfhosted tailscale control server instances / URLs (e.g. Headscale)

### ISSUE THREAD

**Issue by trinity-geology-unstable** [artis3n/ansible-role-tailscale#323]
Headscale is a freely available third-party implementation of the Tailscale control platform which can be self-hosted behind a custom domain. Tailscale actively support the project and enable their use in both their CLI and mobile applications.

It would be great to support the use of these in this ansible role.

**Comment by artis3n** [comment]
I'll update the README to make it clear, but you should set `tailscale_args: --login-server=...` and the role should work with Headscale.

**Comment by artis3n** [comment]
Updated README
