### ISSUE TITLE
[BUG] Galaxy install fails due to wrong download urls (https://github.com/None prefix)

### ISSUE THREAD

**Issue by faevourite** [artis3n/ansible-role-tailscale#383]
**Describe the bug**
Can't install the role from Ansible galaxy.

```
...
Calling Galaxy at https://galaxy.ansible.com/api/
Found API version 'v3, pulp-v3, v1' with Galaxy server default (https://galaxy.ansible.com/api/)
- downloading role 'tailscale', owned by artis3n
Calling Galaxy at https://galaxy.ansible.com/api/v1/roles/?owner__username=artis3n&name=tailscale
Calling Galaxy at https://galaxy.ansible.com/api/v1/roles/3084/versions/?page_size=50
- downloading role from https://github.com/None/tailscale/archive/v4.2.3.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found
[WARNING]: - artis3n.tailscale was NOT installed successfully.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

Note the URL with Github user "None". This shows up on https://galaxy.ansible.com/api/v1/roles/3084/versions/?page_size=50 .

**To Reproduce**
1. ansible-galaxy role install -vvvvv artis3n.tailscale

**Target (please complete the following information):**
 - OS: MacOs
 - Ansible version: 8.4.0
 - `artis3n.tailscale` version: 4.2.0

**Comment by artis3n** [comment]
I can't reproduce this - what does `ansible-galaxy --version` output?

![image](https://github.com/artis3n/ansible-role-tailscale/assets/6969296/7cf132f2-2eb0-4762-a4b0-eff1248bf2ee)

This error suggests the tooling is trying to connect to the "legacy" Ansible Galaxy site, which makes me assume `ansible-galaxy` needs to be updated. The new site changed their APIs.

**Comment by artis3n** [comment]
And actually, I see what appears to be this issue under the bugfixes for `core 2.15.5` - 

> ansible-galaxy info - fix reporting no role found when lookup_role_by_name returns None.

https://github.com/ansible/ansible/blob/v2.15.5/changelogs/CHANGELOG-v2.15.rst#v2-15-5

**Comment by faevourite** [comment]
Huh! I also have ansible-galaxy 2.15.5. I didn't change anything, but today installing works. May have been a temporary issue, I guess? Sorry for the noise, and please feel free to close. Thx for writing this role, btw! ❤️

**Comment by artis3n** [comment]
🤷  Glad it is working now!
