### ISSUE TITLE
[FEAT] Enable auto-update feature

### ISSUE THREAD

**Issue by artis3n** [artis3n/ansible-role-tailscale#386]
Tailscale is releasing beta support for auto-updating clients. 

https://tailscale.com/blog/auto-update-beta/

It requires running

```
tailscale set --auto-update
```

Should we run this if `state` is set to `latest`? It can be passed in as a flag in the `tailscale_args` parameter, but should it do so automatically if state is set to `latest`?

Should it be an explicitly configured separate option? Enabled by default by this role or not?

Collecting feedback on this issue before making a decision.

**Comment by McSim85** [comment]
In my opinion, an additional variable like `tailscale_autoupdate: true` should enable the `--auto-update` flag.
I expect `state: latest` should only upgrade the version when you run the role with `state; latest`.
There is a case where tailscale infra should match security compliance, and auto upgrade is not recommended/allowed.
So, a manual run tole with "state: latest" will allow you to upgrade tailscale manually to the latest version and have more control when you want to have the latest version.

**Comment by artis3n** [comment]
Yeah, I've come to the same decision. It can be added to `tailscale_args` is a user wants. While Tailscale has the feature off by default, this role should mirror that behavior.
