### ISSUE TITLE
[FEAT] after tailscale up, set_fact tailscale_ip

### ISSUE THREAD

**Issue by whysthatso** [artis3n/ansible-role-tailscale#462]
**Is your feature request related to a problem? Please describe.**
Using the tailscale ip later in a playbook run currently makes it necessary to pause/finish the play, set a variable with the tailscale ip, then resume or run another

**Describe the solution you'd like**
as soon as tailscale up succeeds and a tailscale ip is assigned to the device, it should be dynamically added to the ansible_facts, probably via set_fact. then it should be available in later tasks.

**Comment by artis3n** [comment]
Great idea

**Comment by artis3n** [comment]
How do these look to you? https://github.com/artis3n/ansible-role-tailscale/pull/464/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R68

**Comment by whysthatso** [comment]
ah, you beat me to it :D

that looks very thorough and adds a bunch of other useful info. 

i'm wondering about the scope of this role and adding additional features. it's a nice working unit, and feature creep is the plague. 

when thinking about a unit of responsibility of an ansible role, i think i like the idea that assigning facts to a host that sort of programmatically document the outcome of a play run make a lot of sense as the final bracket of the functionality. you could so to speak pipe this output into the next play, very unix-y approach.

this is all just to make sure the additional feature  is justified, and i think your implementation is well in the boundaries of that. so: cool! and thank you for the work you are putting into all this.
