### ISSUE TITLE
Support NixOS

### ISSUE THREAD

**Issue by artis3n** [artis3n/ansible-role-tailscale#99]
https://tailscale.com/kb/1063/install-nixos/

**Comment by Atemu** [comment]
This can be closed.  

NixOS is a fully declarative system already and can be considered an alternative to Ansible.

I don't think Ansible even works on NixOS and even if it did, a NixOS user probably wouldn't want it as these are conceptionally incompatible and would only interfere with each other.

**Comment by artis3n** [comment]
Thank you! I wasn't previously aware of what NixOS is. Doing some reading, it appears as you say.
